In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
# Load the dataset
openfoods_df = pd.read_csv('data_raw/en.openfoodfacts.org.products.tsv', sep='\t',
    on_bad_lines='skip',
    engine='python')

In [8]:
openfoods_df.head()

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,3087.0,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4530.0,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,4559.0,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,16087.0,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,16094.0,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
openfoods_df['countries_en'].value_counts()

countries_en
United States          173154
France                 123960
Switzerland             14932
Germany                  8470
Spain                    5529
                        ...
Australia,Japan             1
Maldives                    1
Cook Islands,France         1
Australia,Malaysia          1
China,Hong Kong             1
Name: count, Length: 779, dtype: int64

In [11]:
de_openfoods_df = openfoods_df[openfoods_df['countries_en'].str.contains('Germany', na=False)].copy()

In [18]:
de_openfoods_df.drop(columns=['countries_en'], inplace=True)

In [19]:
de_openfoods_df.info()

<class 'pandas.DataFrame'>
Index: 9403 entries, 223 to 355958
Columns: 162 entries, code to water-hardness_100g
dtypes: float64(108), str(54)
memory usage: 11.7 MB

In [22]:
de_openfoods_df.head(20)

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
223,2.042464e+07,http://world-en.openfoodfacts.org/product/0000...,twoflower,1489527029,2017-03-14T21:30:29Z,1489527442,2017-03-14T21:37:22Z,Belgische Pralinen,Pralinenmischung,250 g,...,NaN,NaN,NaN,NaN,NaN,NaN,26.0,26.0,NaN,NaN
241,6.910524e+07,http://world-en.openfoodfacts.org/product/0000...,date-limite-app,1466933518,2016-06-26T09:31:58Z,1492939747,2017-04-23T09:29:07Z,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,2.042865e+08,http://world-en.openfoodfacts.org/product/0000...,allfitnessfactory-de,1483099966,2016-12-30T12:12:46Z,1490373567,2017-03-24T16:39:27Z,Mehrkomponeneten Protein 90 C6 Haselnuß,Mehrkomponeneten Protein in Haselnuß Geschmack,"2,5 kg",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,2.042866e+08,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1422378170,2015-01-27T17:02:50Z,1490373621,2017-03-24T16:40:21Z,Mehrkomponeneten Protein 90 C6 Schoko,Mehrkomponeneten Protein in Schoko Geschmack,"2,5 kg",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,2.506330e+08,http://world-en.openfoodfacts.org/product/0000...,allfitnessfactory-de,1484292612,2017-01-13T07:30:12Z,1490373777,2017-03-24T16:42:57Z,Mehrkomponeneten Protein 90 C6 Banane,Mehrkomponeneten Protein in Bananen Geschmack,"2,5 kg",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306,4.609387e+08,http://world-en.openfoodfacts.org/product/0000...,allfitnessfactory-de,1483097990,2016-12-30T11:39:50Z,1490374078,2017-03-24T16:47:58Z,100% Soja Protein Haselnuss,100% Soja Protein Haselnuss Geschmack,2 kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,4.703228e+08,http://world-en.openfoodfacts.org/product/0000...,allfitnessfactory-de,1484302932,2017-01-13T10:22:12Z,1490374052,2017-03-24T16:47:32Z,Whey Protein aus Molke Vanilla,Whey Protein aus Molke Vanille Geschmack,2000g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,5.010506e+08,http://world-en.openfoodfacts.org/product/0000...,allfitnessfactory-de,1484302351,2017-01-13T10:12:31Z,1490373878,2017-03-24T16:44:38Z,Whey Protein aus Molke 1000 Gramm Vanilla,Whey Protein aus Molke 1000 Gramm Vanille Gesc...,1000g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,5.269383e+08,http://world-en.openfoodfacts.org/product/0000...,allfitnessfactory-de,1484301827,2017-01-13T10:03:47Z,1490373794,2017-03-24T16:43:14Z,Whey Protein aus Molke 500 Gramm Vanilla,Whey Protein aus Molke 500 Gramm Vanille Gesch...,500g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369,7.903100e+08,http://world-en.openfoodfacts.org/product/0000...,malikele,1388682187,2014-01-02T17:03:07Z,1446649711,2015-11-04T15:08:31Z,Sour Fruit Gummies,NaN,3.5 oz,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
370,7.903100e+08,http://world-en.openfoodfacts.org/product/0000...,malikele,1388661711,2014-01-02T11:21:51Z,1446649717,2015-11-04T15:08:37Z,Jelly Fish,NaN,3 oz,...,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,NaN,NaN
519,2.042862e+09,http://world-en.openfoodfacts.org/product/0002...,allfitnessfactory-de,1483099130,2016-12-30T11:58:50Z,1490373581,2017-03-24T16:39:41Z,Mehrkomponeneten Protein 90 C6 Vanille,Mehrkomponeneten Protein in Vanille Geschmack,"2,5 kg",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
572,2.983543e+09,http://world-en.openfoodfacts.org/product/0002...,allfitnessfactory-de,1483096645,2016-12-30T11:17:25Z,1490373552,2017-03-24T16:39:12Z,100% Soja Protein Neutral,100% Soja Protein Geschmacksneutral,2 kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7434,1.121001e+10,http://world-en.openfoodfacts.org/product/0011...,bitnapper,1426527941,2015-03-16T17:45:41Z,1497197925,2017-06-11T16:18:45Z,Green pepper sauce,NaN,57 ml,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10465,1.220000e+10,http://world-en.openfoodfacts.org/product/0012...,date-limite-app,1440070244,2015-08-20T11:30:44Z,1461430702,2016-04-23T16:58:22Z,Baguette-Brötchen,NaN,540 g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13159,1.600050e+10,http://world-en.openfoodfacts.org/product/0016...,smias,1485523993,2017-01-27T13:33:13Z,1490018715,2017-03-20T14:05:15Z,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,11.0,11.0,NaN,NaN
13249,1.622990e+10,http://world-en.openfoodfacts.org/product/0016...,anticultist,1477773100,2016-10-29T20:31:40Z,1477773238,2016-10-29T20:33:58Z,Kokosnussmilch,NaN,400ml,...,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,NaN,NaN
15801,1.996269e+10,http://world-en.openfoodfacts.org/product/0019...,hangy,1476467958,2016-10-14T17:59:18Z,1477745908,2016-10-29T12:58:28Z,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15972,2.024212e+10,http://world-en.openfoodfacts.org/product/0020...,davidak,1497341615,2017-06-13T08:13:35Z,1502007796,2017-08-06T08:23:16Z,Kartoffel Snack mit Steinpilzen & Crème fraîche,NaN,47 g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18977,2.120000e+10,http://world-en.openfoodfacts.org/product/0021...,date-limite-app,1472812205,2016-09-02T10:30:05Z,1483050909,2016-12-29T22:35:09Z,Mozzarella 45% Fett i.Tr.,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
de_openfoods_df['categories'].value_counts()

categories
Brotaufstriche                                                                                               81
Käse                                                                                                         72
Joghurt                                                                                                      70
Kekse                                                                                                        57
Milchprodukte,Käse,Frischkäse                                                                                55
                                                                                                             ..
Salty snacks,Appetizers,Chips and fries,Crisps,Zwiebelringe                                                   1
de:Nahrungsergänzungsmittel,Dietary supplements,fr:Compléments alimentaires                                   1
Energy Drinks                                                                                                 1
Xylitol                                                                                                       1
Pflanzliche Lebensmittel und Getränke,Pflanzliche Lebensmittel,Getreide und Kartoffeln,Brote,Semmelbrösel     1
Name: count, Length: 2907, dtype: int64

In [24]:
de_openfoods_df = de_openfoods_df.dropna(subset=['categories', 'product_name'], how='all')

In [25]:
de_openfoods_df

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
223,2.042464e+07,http://world-en.openfoodfacts.org/product/0000...,twoflower,1489527029,2017-03-14T21:30:29Z,1489527442,2017-03-14T21:37:22Z,Belgische Pralinen,Pralinenmischung,250 g,...,NaN,NaN,NaN,NaN,NaN,NaN,26.0,26.0,NaN,NaN
276,2.042865e+08,http://world-en.openfoodfacts.org/product/0000...,allfitnessfactory-de,1483099966,2016-12-30T12:12:46Z,1490373567,2017-03-24T16:39:27Z,Mehrkomponeneten Protein 90 C6 Haselnuß,Mehrkomponeneten Protein in Haselnuß Geschmack,"2,5 kg",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,2.042866e+08,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1422378170,2015-01-27T17:02:50Z,1490373621,2017-03-24T16:40:21Z,Mehrkomponeneten Protein 90 C6 Schoko,Mehrkomponeneten Protein in Schoko Geschmack,"2,5 kg",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,2.506330e+08,http://world-en.openfoodfacts.org/product/0000...,allfitnessfactory-de,1484292612,2017-01-13T07:30:12Z,1490373777,2017-03-24T16:42:57Z,Mehrkomponeneten Protein 90 C6 Banane,Mehrkomponeneten Protein in Bananen Geschmack,"2,5 kg",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306,4.609387e+08,http://world-en.openfoodfacts.org/product/0000...,allfitnessfactory-de,1483097990,2016-12-30T11:39:50Z,1490374078,2017-03-24T16:47:58Z,100% Soja Protein Haselnuss,100% Soja Protein Haselnuss Geschmack,2 kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354914,9.314507e+12,http://world-en.openfoodfacts.org/product/9314...,hangy,1447872089,2015-11-18T18:41:29Z,1501968746,2017-08-05T21:32:26Z,Ganze Aprikosen,NaN,200g,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,NaN,NaN
354975,9.316985e+12,http://world-en.openfoodfacts.org/product/9316...,twoflower,1453737717,2016-01-25T16:01:57Z,1453737846,2016-01-25T16:04:06Z,Speisequark Magerstufe,Speisequark Magerstufe,500 g,...,NaN,NaN,NaN,NaN,NaN,NaN,-5.0,-5.0,NaN,NaN
355591,9.422769e+07,http://world-en.openfoodfacts.org/product/9422...,openfoodfacts-contributors,1446543880,2015-11-03T09:44:40Z,1446543924,2015-11-03T09:45:24Z,Erdbeere,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
355618,9.487272e+12,http://world-en.openfoodfacts.org/product/9487...,kakao,1497966299,2017-06-20T13:44:59Z,1501427248,2017-07-30T15:07:28Z,Cantuccini mit Schokolade,Gebäck mit Schokolade,150 g,...,NaN,NaN,NaN,NaN,NaN,NaN,17.0,17.0,NaN,NaN
355958,9.780201e+12,http://world-en.openfoodfacts.org/product/9780...,hg,1488617055,2017-03-04T08:44:15Z,1488617103,2017-03-04T08:45:03Z,Zuckerfrei,NaN,100g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
de_openfoods_df['categories'].value_counts()

### Remove alcoholic beverages
We're removing all products that are categorized as alcoholic beverages, as they are not included in the Destatic Dataset. This is done to ensure that our analysis is consistent and focused on the types of products that are relevant to our study.

In [31]:
alcohol= ["Beverages,Alcoholic beverages,Beers"
,"Beverages,Alcoholic beverages,Beers,Beers from Germany"
,"Beverages,Alcoholic beverages,Beers,Beers with fruits,Cherry beers,Flavored beers,Bières lambic"
,"Beverages,Alcoholic beverages,Beers,Belgian beers,Wheat beers"
,"Beverages,Alcoholic beverages,Beers,Bier"
,"Beverages,Alcoholic beverages,Beers,Flavored beers"
,"Beverages,Alcoholic beverages,Beers,Lagers"
,"Beverages,Alcoholic beverages,Beers,Lagers,Bières de haute fermentation"
,"Beverages,Alcoholic beverages,Beers,Lagers,fr:Bières de fermentation haute"
,"Beverages,Alcoholic beverages,Beers,Organic beers,Bières au chanvre"
,"Beverages,Alcoholic beverages,Beers,Red beers"
,"Beverages,Alcoholic beverages,Hard liquors,fr:Eaux-de-vie,Whisky"
,"Beverages,Alcoholic beverages,Wines,French wines,Red wines"
,"Beverages,Alcoholic beverages,Wines,Red wines"
,"Beverages,Alcoholic beverages,Wines,Red wines,Chianti"
,"Beverages,Alcoholic beverages,Wines,Red wines,it:Montepulciano d'abruzzo"
,"Beverages,Alcoholic beverages,Wines,White wines,Wines from Italy"
,"Beverages,Alcoholic beverages,Wines,Wines from Austria,de:Niederösterreich"
,"Beers"
,"Beers from Germany"
,"Beers from Germany,Craft beers,Lagers"
,"Beers from Germany,Lagers"
,"Beers from Germany,Organic beers"
,"Beers from Germany,Weissbier"
,"Beers from Stralsund"
,"Bier"
,"Biere"
,"Biere,Beers from Germany,Stout"
,"Bieren,Alcoholvrije bieren"
,"Biermischgetränk"
,"Biermischgetränk,Biere"
,"Biermischgetränke"
,"Bières blondes"
,"Bières,Bières fortes,Boissons,Boissons alcoolisées"
,"Boissons,Boissons alcoolisées,Alcools forts,Eaux-de-vie,Whiskys,Whisky écossais"
,"Boissons,Boissons alcoolisées,Bières,Bieres aromatisées aux fruits,Bières françaises,Bières ambrées,Bières à la chataigne,Bières corses"
,"Boissons,Boissons alcoolisées,Bières,Bières blondes"
,"Boissons,Boissons alcoolisées,Bières,Bières blondes,Bières belges"
,"Boissons,Boissons alcoolisées,Bières,Bières blondes,Bières fortes"
,"Boissons,Boissons alcoolisées,Bières,Pilsener"
,"Boissons,Boissons alcoolisées,Liqueurs"
,"Boissons,Boissons alcoolisées,Vins,Vins effervescents,Vins mousseux"
,"Craft beers,Strong beers"
,"Getränke,Alcoholic beverages,Bier"
,"Getränke,Alkoholische Getränke"
,"Getränke,Alkoholische Getränke,Biere"
,"Getränke,Alkoholische Getränke,Biere,Alkoholfreie Getränke,Beers from Germany,Bayerische Biere,Alkoholfreie Weizenbiere"
,"Getränke,Alkoholische Getränke,Biere,Artisan products,Artisanal spirits,Craft beers"
,"Getränke,Alkoholische Getränke,Biere,Artisan products,Artisanal spirits,Craft beers,Obergäriges Bier"
,"Getränke,Alkoholische Getränke,Biere,Beers from Germany"
,"Getränke,Alkoholische Getränke,Biere,Beers from Germany,Bayerische Biere"
,"Getränke,Alkoholische Getränke,Biere,Beers from Germany,Bayerische Biere,Strong beers,Weissbier"
,"Getränke,Alkoholische Getränke,Biere,Beers from Germany,Lagers"
,"Getränke,Alkoholische Getränke,Biere,Beers from Germany,Weissbier"
,"Getränke,Alkoholische Getränke,Biere,Pilsner"
,"Getränke,Alkoholische Getränke,Biere,Strong beers"
,"Getränke,Alkoholische Getränke,Biere,Strong beers,Beers from Germany"
,"Getränke,Alkoholische Getränke,Biere,Ungezuckerte Getränke"
,"Getränke,Alkoholische Getränke,Biere,Weissbier"
,"Getränke,Alkoholische Getränke,Biere,Weissbier,Beers from Germany"
,"Getränke,Alkoholische Getränke,Hard liquors"
,"Getränke,Alkoholische Getränke,Hard liquors,Eaux-de-vie,Brandys,Eaux-de-vie"
,"Getränke,Alkoholische Getränke,Hard liquors,fr:Eaux-de-vie"
,"Getränke,Alkoholische Getränke,Liqueurs"
,"Getränke,Alkoholische Getränke,Liqueurs,fr:Liqueur au whisky"
,"Getränke,Alkoholische Getränke,Schnäpse,Gins"
,"Getränke,Alkoholische Getränke,Schnäpse,Liqueurs"
,"Getränke,Alkoholische Getränke,Weine"
,"Getränke,Alkoholische Getränke,Weine,Bordeauxweine"
,"Getränke,Alkoholische Getränke,Weine,Federweißer"
,"Getränke,Alkoholische Getränke,Weine,Französische Weine,Roteweine,Pomerol"
,"Getränke,Alkoholische Getränke,Weine,Französische Weine,Weißwein"
,"Getränke,Alkoholische Getränke,Weine,Roteweine"
,"Getränke,Alkoholische Getränke,Weine,Roteweine,Italienische Weine"
,"Getränke,Alkoholische Getränke,Weine,Roteweine,Spanische Weine"
,"Getränke,Alkoholische Getränke,Weine,Roteweine,Wein"
,"Getränke,Alkoholische Getränke,Weine,Roteweine,it:Provincia di Verona"
,"Getränke,Alkoholische Getränke,Weine,Schaumweine"
,"Getränke,Alkoholische Getränke,Weine,Spanische Weine"
,"Getränke,Alkoholische Getränke,Weine,Weißwein,Wines from Germany,Württemberg"
,"Getränke,Alkoholische Getränke,Weine,Wines from Germany"
,"Liqueurs"
,"Liqueurs,Tequilas"
,"Organic beers,Beers from Germany"
,"Roteweine"
,"Roteweine,Italienische Weine"
,"Roteweine,Italienische Weine,it:Veneto"
,"Roteweine,Rheinhessen"
,"Roteweine,Spanische Weine"
,"Rum"
,"Rums"
,"Scottish Whisky"
,"Sekt"
,"Vollbier,Craft Beer"
,"Weine"
,"Weine,Rotwein"
,"Weine,Weißwein"
,"Weizenbiere"
,"Weißwein"
,"Weißwein,Baden"
,"Weißwein,Wines from Germany"
,"Wheat beers"
,"Wodkas"
,"en:Beers"
,"en:Rums"
,"es:Rotwein"
,"es:Vino Rasgón de la Tierra de Castilla,es:Vino de la Tierra de Castilla,en:Wine"
,"fr:Bières avec des fruits"
,"fr:vin"
,"fr:vin blanc"
,"japanese beer"
,"red wine,Wine from Macedonia"
,"weine"
,"甜類零食"
,"Alkoholfreie Biere"
,"Alkoholfreies Bier"
,"Alkoholische Getränke"
]

In [32]:
de_openfoods_df = de_openfoods_df[~de_openfoods_df['categories'].isin(alcohol)]

In [33]:
de_openfoods_df['categories'].value_counts()

categories
Brotaufstriche                                                                                               81
Käse                                                                                                         72
Joghurt                                                                                                      70
Kekse                                                                                                        57
Milchprodukte,Käse,Frischkäse                                                                                55
                                                                                                             ..
Salty snacks,Appetizers,Chips and fries,Crisps,Zwiebelringe                                                   1
de:Nahrungsergänzungsmittel,Dietary supplements,fr:Compléments alimentaires                                   1
Energy Drinks                                                                                                 1
Xylitol                                                                                                       1
Pflanzliche Lebensmittel und Getränke,Pflanzliche Lebensmittel,Getreide und Kartoffeln,Brote,Semmelbrösel     1
Name: count, Length: 2790, dtype: int64