In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
# Load the dataset
openfoods_df = pd.read_csv('data_raw/en.openfoodfacts.org.products.tsv', sep='\t',
    on_bad_lines='skip',
    engine='python')

In [8]:
openfoods_df.head()

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,3087.0,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4530.0,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,4559.0,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,16087.0,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,16094.0,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
openfoods_df['countries_en'].value_counts()

countries_en
United States          173154
France                 123960
Switzerland             14932
Germany                  8470
Spain                    5529
                        ...
Australia,Japan             1
Maldives                    1
Cook Islands,France         1
Australia,Malaysia          1
China,Hong Kong             1
Name: count, Length: 779, dtype: int64

In [11]:
de_openfoods_df = openfoods_df[openfoods_df['countries_en'].str.contains('Germany', na=False)].copy()

In [15]:
de_openfoods_df.info()

<class 'pandas.DataFrame'>
Index: 9403 entries, 223 to 355958
Columns: 163 entries, code to water-hardness_100g
dtypes: float64(108), str(55)
memory usage: 11.8 MB

In [16]:
de_openfoods_df.head()

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
223,20424640.0,http://world-en.openfoodfacts.org/product/0000...,twoflower,1489527029,2017-03-14T21:30:29Z,1489527442,2017-03-14T21:37:22Z,Belgische Pralinen,Pralinenmischung,250 g,...,NaN,NaN,NaN,NaN,NaN,NaN,26.0,26.0,NaN,NaN
241,69105241.0,http://world-en.openfoodfacts.org/product/0000...,date-limite-app,1466933518,2016-06-26T09:31:58Z,1492939747,2017-04-23T09:29:07Z,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,204286484.0,http://world-en.openfoodfacts.org/product/0000...,allfitnessfactory-de,1483099966,2016-12-30T12:12:46Z,1490373567,2017-03-24T16:39:27Z,Mehrkomponeneten Protein 90 C6 Haselnuß,Mehrkomponeneten Protein in Haselnuß Geschmack,"2,5 kg",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,204286644.0,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1422378170,2015-01-27T17:02:50Z,1490373621,2017-03-24T16:40:21Z,Mehrkomponeneten Protein 90 C6 Schoko,Mehrkomponeneten Protein in Schoko Geschmack,"2,5 kg",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,250632969.0,http://world-en.openfoodfacts.org/product/0000...,allfitnessfactory-de,1484292612,2017-01-13T07:30:12Z,1490373777,2017-03-24T16:42:57Z,Mehrkomponeneten Protein 90 C6 Banane,Mehrkomponeneten Protein in Bananen Geschmack,"2,5 kg",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
de_openfoods_df['categories'].value_counts()

categories
Brotaufstriche                                                                                               81
Käse                                                                                                         72
Joghurt                                                                                                      70
Kekse                                                                                                        57
Milchprodukte,Käse,Frischkäse                                                                                55
                                                                                                             ..
Salty snacks,Appetizers,Chips and fries,Crisps,Zwiebelringe                                                   1
de:Nahrungsergänzungsmittel,Dietary supplements,fr:Compléments alimentaires                                   1
Energy Drinks                                                                                                 1
Xylitol                                                                                                       1
Pflanzliche Lebensmittel und Getränke,Pflanzliche Lebensmittel,Getreide und Kartoffeln,Brote,Semmelbrösel     1
Name: count, Length: 2907, dtype: int64